version: "3.9"

services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
    ports:
      - "5436:5432"

  api:
    container_name: todo-java
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./ :/app
