version: "3.9"

services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - ./data/db:/var/lib/postgresql/datadi
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"